apiVersion: apps/v1
kind: Deployment
metadata:
  name: appexample
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: appexample
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always 

